create table if not exists vendors
(
    id int generated by default as identity primary key,
    name varchar(110) not null unique,
    created_datetime timestamp,
    modified_datetime timestamp
);

create table if not exists parts
(
    id int generated by default as identity primary key,
    nickname varchar(255),
    actual_name varchar(255),
    part_number varchar(55),
    vendor_id int,
    cost numeric(10,3),
    price numeric(10,3),
    unit_of_measure varchar(10),
    created_datetime timestamp,
    modified_datetime timestamp
);

create table if not exists products
(
    id int generated by default as identity primary key,
    name varchar(255) not null unique,
    created_datetime timestamp,
    modified_datetime timestamp
);